#홈페이지에서 API서비스 신청시 받은 Appkey, Appsecret 값 설정
APP_KEY: "PS1684F7bZW7zwhwFCnsn7ZyaUTDEMYfDoXT"
APP_SECRET: "gg+6wntY6Yop5E50nvXeX1m7ckl+H/4YwgLLhuTQMlI4cDQUHG/5ZbZ3Sc2wOHQ1XQJE/TgEBc8ezRpRMpKokT0GrhSkqTeXUsmsE2tzZP8GxFBUXcBRy87RGz1MMa5ffDWqVPt+gG5Wu5LIC2H7rmFaya/g1DJJSkto4styILVieo+W8/s="

#계좌번호 앞 8자리
CANO: "50078082"
#계좌번호 뒤 2자리
ACNT_PRDT_CD: "01"

#실전투자
#URL_BASE: "https://openapi.koreainvestment.com:9443"

#모의투자
URL_BASE: "https://openapivts.koreainvestment.com:29443"

# URL_BASE: "https://openapivts.koreainvestment.com:29443"

#디스코드 웹훅 URL
DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/1072756771304767538/X2pSMzSADNhBjwE55btoAHbNEqHzQiEr0lkcsslwqzuNw4SiHYN4YN0-mPvvWCstTAw_"